version: '3.8'

services:
  web:
    container_name: web
    image: ngthotuan/my-website
    build: .
    restart: always
    ports:
      - 8080:${SERVER_PORT}
    volumes:
      - /appdata/user-upload:/appdata/user-upload
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
  db:
    image: clutteredcode/mongo-alpine
    container_name: db
    environment:
      MONGO_USERNAME: ${DB_USER}
      MONGO_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /appdata/db/mongo_nguyenthotuan.me:/data/db
  db_manager:
    container_name: db_manager
    image: mongo-express
    restart: always
    ports:
      - ${DB_MANAGER_PORT}:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_MANAGER_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_MANAGER_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${DB_HOST}
      ME_CONFIG_MONGODB_PORT: ${DB_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}