version: '3.8'

services:
  web:
    container_name: web
    image: ngthotuan/my-website:v1.1.0
    build: .
    restart: always
    networks:
      - mywebsite-network
    ports:
      - 8080:${SERVER_PORT}
    env_file:
      - .env
    volumes:
      - /appdata/user-upload:/app/user-upload
    depends_on:
      - db
  db:
    container_name: db
    image: mongo
    restart: always
    networks:
      - mywebsite-network
    volumes:
      - /appdata/db/mongo_nguyenthotuan.me:/data/db
      - /appdata/db/mongo_nguyenthotuan.me/configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
  db_manager:
    container_name: db_manager
    image: mongo-express
    restart: always
    networks:
      - mywebsite-network
    ports:
      - ${DB_MANAGER_PORT}:8081
    depends_on:
      - db
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_MANAGER_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_MANAGER_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${DB_HOST}
      ME_CONFIG_MONGODB_PORT: ${DB_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
networks:
  mywebsite-network:
    name: mywebsite-network