FROM ngthotuan/node-mongo-alpine
ENV NODE_ENV=production
RUN npm install pm2 -g

RUN adduser -D node
RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
RUN mkdir -p /appdata && chmod 777 /appdata

WORKDIR /home/node/app

COPY package*.json ./

USER node


RUN npm install --production

COPY .env .
COPY ecosystem.config.js .
COPY src src

EXPOSE 8080

#CMD [ "node", "src/bin/www" ]
CMD ["pm2-runtime", "ecosystem.config.js", "--env", "production"]