version: '3.8'

services:
  web:
    container_name: web
    image: ngthotuan/my-website
    build: .
    restart: always
    volumes:
      - ./user-upload:/app/user-upload
    ports:
      - 8080:3000
    env_file:
      - .env